### ISSUE TITLE
harp_import_test_fuzzer: ASSERT: (char *)gs.pos < (char *)gs.end

### ISSUE THREAD

**Issue by schwehr** [stcorp/harp#218]
Not sure if this is something that harp can catch or it has to be solved in netcdf.  It's way too short to be a valid netcdf file for harp processing at 8 bytes long.

```
    #7 0x55e7392518d9 in nc_get_NC third_party/netcdf/libsrc/v1hpg.c:1523:2
    #8 0x55e7391b6c74 in NC3_open third_party/netcdf/libsrc/nc3internal.c:1226:11
    #9 0x55e73917150f in NC_open third_party/netcdf/libdispatch/dfile.c:2143:11
    #10 0x55e73917092b in nc_open third_party/netcdf/libdispatch/dfile.c:672:11
    #11 0x55e738f46b30 in harp_import_netcdf third_party/stcorp_harp/libharp/harp-netcdf.c:810:14
    #12 0x55e738d2e3c4 in harp_import_test third_party/stcorp_harp/libharp/harp.c:671:22
    #13 0x55e738d2bd3d in LLVMFuzzerTestOneInput third_party/stcorp_harp/fuzz/harp_import_test_fuzzer.cc:21:3
```

[testcase-6303190298918912.zip](https://github.com/stcorp/harp/files/4625895/testcase-6303190298918912.zip)

**Comment by svniemeijer** [comment]
This is something that should be resolved in the netcdf library itself.
