### ISSUE TITLE
harp_program_from_string_fuzzer: Direct-leak in harp_program_new

### ISSUE THREAD

**Issue by schwehr** [stcorp/harp#219]
```
==234513==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #1 0x55710a44067e in harp_program_new third_party/stcorp_harp/libharp/harp-program.c:47:31
    #2 0x55710a4265d2 in harp_operation_parser_parse libharp/harp-operation-parser.y:1682:17
    #3 0x55710a430235 in harp_program_from_string libharp/harp-operation-parser.y:1700:9
    #4 0x55710a229bcc in LLVMFuzzerTestOneInput third_party/stcorp_harp/fuzz/harp_program_from_string_fuzzer.cc:19:3
```

[testcase-4831660308955136.zip](https://github.com/stcorp/harp/files/4674444/testcase-4831660308955136.zip)

Was https://github.com/stcorp/coda/issues/74

**Comment by svniemeijer** [comment]
I think this is a duplicate of #217 (which was already solved)

**Comment by schwehr** [comment]
My tools currently say that #217 was fixed and this one is not.  That one was `?`.  This one is just a \0 byte.

**Comment by svniemeijer** [comment]
I can't seem to reproduce it. What is the return value of `harp_program_from_string` for you? Are you calling `harp_program_delete` yourself in your test script on the returned `harp_program` variable when the parsing was successful?

**Comment by schwehr** [comment]
I was missing `harp_program_delete()`.  Was:

```c++
  extern "C" int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
  const std::string operations(reinterpret_cast<const char *>(data), size);

  harp_init();
  auto done = absl::MakeCleanup([] { harp_done(); });

  harp_program *program;
  harp_program_from_string(operations.c_str(), &program);
  return 0;
}
```

Now:

```c++
  extern "C" int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
  const std::string operations(reinterpret_cast<const char *>(data), size);

  harp_init();
  auto done = absl::MakeCleanup([] { harp_done(); });

  harp_program *program;
  harp_program_from_string(operations.c_str(), &program);

  if (program == nullptr) {
    return 0;
  }

  // TODO(schwehr): Do something with the program.

  harp_program_delete(program);  // TODO(schwehr): Switch to MakeCleanup.

  return 0;
}
```

**Comment by svniemeijer** [comment]
That is not the right way to check for things. The variable `program` should not be dereferenced if `harp_program_from_string` returns a non-zero return value.

You should use:

```
if (harp_program_from_string(operations.c_str(), &program) == 0)
{
    harp_program_delete(program);
}

```

**Comment by schwehr** [comment]
Also needed to set `program` to `nullptr` before the call.

```c++
  harp_program *program = nullptr;
```

**Comment by schwehr** [comment]
There is no need for the extra scope in the case of success, so now it's this.  I try to do all error checking first and return if error as soon as possible.

```c++
extern "C" int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
  const std::string operations(reinterpret_cast<const char *>(data), size);

  harp_init();
  auto done = absl::MakeCleanup([] { harp_done(); });

  harp_program *program = nullptr;
  if (harp_program_from_string(operations.c_str(), &program) != 0) {
    return 0;
  }

  // TODO(schwehr): Do something with the program.

  harp_program_delete(program);  // TODO(schwehr): Switch to MakeCleanup.

  return 0;
}
```

**Comment by schwehr** [comment]
verified the fix to my fuzzer.
