### ISSUE TITLE
harp_program_from_string_fuzzer: leak

### ISSUE THREAD

**Issue by schwehr** [stcorp/harp#226]
```
LeakSanitizer: detected memory leaks

Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #1 0x5609022edcde in harp_operation_point_distance_filter_new third_party/stcorp_harp/libharp/harp-operation.c:2522:57
    #2 0x56090230f21e in harp_operation_parser_parse libharp/harp-operation-parser.y:1258:17
    #3 0x56090231e7e5 in harp_program_from_string libharp/harp-operation-parser.y:1702:9
    #4 0x5609020782f0 in LLVMFuzzerTestOneInput third_party/stcorp_harp/fuzz/harp_program_from_string_fuzzer.cc:19:7
```

leak-a7516deaa90a4c3d226b6bb724885d68e75c6aa:

```c
point_distance(0,0,5[])
```

**Comment by svniemeijer** [comment]
Fixed in 243d3783488559f97eff6e294209a82f2e2a59af
